version: "3.8"
services:
  redis:
    image: redis:7
    container_name: redis_ai_seo_gpt
    networks:
      - AI_SEO
  celery:
    container_name: celery_ai_seo_gpt
    build:
      context: .
    command: ["celery", "-A", "app.celery_app", "worker", "--loglevel=INFO", "-P", "gevent"]
    depends_on:
      - redis
    networks:
      - AI_SEO
  unifier:
    container_name: ai_seo_gpt
    build:
      context: .
      dockerfile: Dockerfile
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery
    networks:
      - AI_SEO
networks:
  AI_SEO:
    external: True
    name: "AI_SEO"